version: "3.7"
services:
  web:
    build: .
    working_dir: /var/www/html
    volumes:
       - ./file-web:/var/www/html/
    networks:
      proxy_net:
      int_net:
    healthcheck:
      test: curl -f http://localhost/ || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
  db:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: r89sqNRv13L9
      MYSQL_DATABASE: dbkuasai
      MYSQL_USER: cilsykuasaiuser
      MYSQL_PASSWORD: cilsykuasaipassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      proxy_net:
      int_net:
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 1s
      retries: 120
  proxy:
    volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      proxy_net:
    healthcheck:
      test: curl -f http://localhost/ || exit 0
      interval: 5s
      timeout: 10s
      retries: 3
  pma:
    environment:
      DATABASE_HOST: db
      DATABASE_PORT_NUMBER: 3306
    volumes:
      - pma-data:/bitnami/mariadb
    networks:
      int_net:
      proxy_net:
    healthcheck:
      test: curl -f http://pma:8080/ || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
volumes:
  db-data:
  pma-data:
networks:
  proxy_net:
  int_net:

